name: compliance

on:
  - push
  - workflow_dispatch

jobs:
  verify-gomodtidy-nochanges:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: nix-shell --pure --run 'go mod tidy'
      - run: git diff --exit-code

  check-licenses:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: |
          CMD='\
            GOPATH="$PWD/.gopath" go install github.com/google/go-licenses@latest && \
            GOROOT="$(go env GOROOT)" "$PWD/.gopath/bin/go-licenses" check ./... \
              --include_tests \
              --ignore "$(go list -m)$LICENSES_IGNORE_EXTRA" \
              --allowed_licenses="\
                  MIT \
                , Apache-2.0 \
                , ISC \
                , BSD-2-Clause \
                , BSD-3-Clause \
                , Unlicense \
                , MPL-2.0 \
              " \
          '
          nix-shell --pure --run "$CMD"

  govulncheck:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: |
          nix-shell --pure -p go govulncheck gcc --run 'govulncheck -test ./...'

  nancy:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: |
          CMD='\
            GOPATH="$PWD/.gopath" go install github.com/sonatype-nexus-community/nancy@latest && \
            go list -json -m all | "$PWD/.gopath/bin/nancy" sleuth \
          '
          nix-shell --pure --run "$CMD"
