name: lint

on:
  - push
  - workflow_dispatch

jobs:
  go-vet:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: nix-shell --pure --run 'go vet -v ./...'

  golangci-lint:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: nix-shell --pure --run 'make lint'

  ls-lint:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: |
          cat > .ls-lint.yml <<EOF
            ls:
              .go: snake_case
          EOF
      - run: nix-shell --pure -p ls-lint --run 'command -v ls_lint &> /dev/null && ls_lint || ls-lint'

  goptrcmp:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: |
          CMD='\
            GOPATH="$PWD/.gopath" go install github.com/w1ck3dg0ph3r/goptrcmp/cmd/goptrcmp@latest && \
            "$PWD/.gopath/bin/goptrcmp" ./... \
          '
          nix-shell --pure --run "$CMD" || true # TODO: Fail again once Go 1.24 is supported, see https://github.com/w1ck3dg0ph3r/goptrcmp/issues/3

  untypedconst:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: |
          CMD='\
            GOPATH="$PWD/.gopath" go install github.com/jiftechnify/untypedconst/cmd/untypedconst@latest && \
            "$PWD/.gopath/bin/untypedconst" ./... \
          '
          nix-shell --pure --run "$CMD" || true # TODO: Fail again once Go 1.24 is supported, see https://github.com/jiftechnify/untypedconst/issues/10

  govanish:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: |
          CMD='\
            GOPATH="$PWD/.gopath" go install github.com/sivukhin/govanish@latest && \
            "$PWD/.gopath/bin/govanish" \
          '
          nix-shell --pure --run "$CMD" || true # TODO: Fail again once Go 1.24 is supported, see https://github.com/sivukhin/govanish/issues/3
